apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pocdevops
  namespace: pocdevops
  labels:
    app: pocdevops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: pocdevops-service
    spec:
      containers:
      - name: pocdevops-service
        image: gcr.io
        ports:
        - containerPort: 8080
